/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.asset.addLabel;

import GUI.asset.newAsset.*;
import GUI.utility.ScrollableListPanel;
import asset.Asset;
import asset.AssetCatalogue;
import exceptions.DuplicatedValueException;
import java.awt.ComponentOrientation;
import java.awt.font.TextAttribute;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import label.AttachedLabel;
import label.Label;
import label.LabelCatalogue;

/**
 *
 * @author bagher
 */
public class AssetAttachLabelFrame extends javax.swing.JFrame {

    private ScrollableListPanel labelScrollPane;
    private ScrollableListPanel assetScrollPane;
    private ScrollableListPanel valueScrollPane;
    private AttachedLabel attachedLabel;
    /**
     * Creates new form NewAssetFrame
     */
    public AssetAttachLabelFrame() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e) {
          System.out.println("Error setting native LAF: " + e);
        }
        initComponents();
        attachedLabel = new AttachedLabel();
        assetScrollPane = new ScrollableListPanel("نام دارایی", true);
        labelScrollPane = new ScrollableListPanel("نام برچسب", true);
        valueScrollPane = new ScrollableListPanel("مقدار برچسب", false);
        assetScrollPane.reloadValues(AssetCatalogue.getInstace().getAssets().toArray());
        labelScrollPane.reloadValues(LabelCatalogue.getInstace().getLabels().toArray());
        valueScrollPane.reloadValues(attachedLabel.getValues());
        chooseAsset.add(assetScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 270, 190));
        chooseLabel.add(labelScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 270, 190));
        chooseValue.add(valueScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 270, 190));
        StyledDocument doc = hintPane.getStyledDocument();
        SimpleAttributeSet right = new SimpleAttributeSet();
        StyleConstants.setAlignment(right, StyleConstants.ALIGN_RIGHT);
        doc.setParagraphAttributes(0, doc.getLength(), right, false);
        hintPane.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attachAssetLabel = new javax.swing.JTabbedPane();
        chooseAsset = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        chooseLabel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        chooseValue = new javax.swing.JPanel();
        addValueButton = new javax.swing.JButton();
        labelValueTextField = new javax.swing.JTextField();
        attachLabelButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hintPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        attachAssetLabel.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        attachAssetLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attachAssetLabelMouseClicked(evt);
            }
        });

        chooseAsset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Web Yekan", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("الصاق برچسب به دارایی، انتخاب دارایی");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chooseAsset.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 510, 70));

        attachAssetLabel.addTab("۱- انتخاب دارایی", chooseAsset);

        chooseLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Web Yekan", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("الصاق برچسب به دارایی، انتخاب برچسب");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chooseLabel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 510, 70));

        attachAssetLabel.addTab("۲- انتخاب برچسب", chooseLabel);

        chooseValue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addValueButton.setBackground(new java.awt.Color(60, 0, 91));
        addValueButton.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        addValueButton.setForeground(new java.awt.Color(1, 1, 1));
        addValueButton.setText("اضافه‌کردن");
        addValueButton.setFocusPainted(false);
        addValueButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        addValueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addValueButtonActionPerformed(evt);
            }
        });
        chooseValue.add(addValueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, 30));

        labelValueTextField.setFont(new java.awt.Font("XB Zar", 0, 15)); // NOI18N
        labelValueTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        chooseValue.add(labelValueTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 170, -1));

        attachLabelButton.setBackground(new java.awt.Color(60, 0, 91));
        attachLabelButton.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        attachLabelButton.setForeground(new java.awt.Color(1, 1, 1));
        attachLabelButton.setText("الصاق برچسب به دارایی");
        attachLabelButton.setFocusPainted(false);
        attachLabelButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        attachLabelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachLabelButtonActionPerformed(evt);
            }
        });
        chooseValue.add(attachLabelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 150, 30));

        jLabel5.setFont(new java.awt.Font("Web Yekan", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("الصاق برچسب به دارایی، انتخاب مقدار");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chooseValue.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 510, 70));

        jLabel51.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel51.setText("مجموعه مقادیر الصاق شده");
        chooseValue.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 170, -1));

        jLabel52.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel52.setText("مقادیر ممکن برچسب");
        jLabel52.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        chooseValue.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 150, -1));

        hintPane.setFont(new java.awt.Font("XB Zar", 0, 15)); // NOI18N
        hintPane.setText("هنوز برچسی انتخاب نشده است.");
        jScrollPane2.setViewportView(hintPane);

        chooseValue.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 210, 290));

        attachAssetLabel.addTab("۳- انتخاب مقدار", chooseValue);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(attachAssetLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(attachAssetLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attachAssetLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attachAssetLabelMouseClicked
        if(attachedLabel.getLabel() != labelScrollPane.getSelectedItem())
            attachedLabel.setLabel((Label)labelScrollPane.getSelectedItem());
        if(attachedLabel.getLabel()!= null){
            Object[] objects = ((Label)labelScrollPane.getSelectedItem()).getValues();
            String hint = "";
            for(Object object: objects)
                hint += "• " + object.toString() + "\n";
            hintPane.setText(hint);
            if(((Label)labelScrollPane.getSelectedItem()).getType().getTypeName().equals("String")){
                StyledDocument doc = hintPane.getStyledDocument();
                SimpleAttributeSet right = new SimpleAttributeSet();
                StyleConstants.setAlignment(right, StyleConstants.ALIGN_RIGHT);
                doc.setParagraphAttributes(0, doc.getLength(), right, false);
                hintPane.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
            }else{
                StyledDocument doc = hintPane.getStyledDocument();
                SimpleAttributeSet right = new SimpleAttributeSet();
                StyleConstants.setAlignment(right, StyleConstants.ALIGN_LEFT);
                doc.setParagraphAttributes(0, doc.getLength(), right, false);
                hintPane.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
            }
        }
        valueScrollPane.reloadValues(attachedLabel.getValues());
    }//GEN-LAST:event_attachAssetLabelMouseClicked

    private void addValueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addValueButtonActionPerformed
        if(attachedLabel.getLabel() == null){
            JOptionPane.showMessageDialog(null, "برچسبی انتخاب نشده است.", "خطا", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            if(attachedLabel.addValue(labelValueTextField.getText()) == false)
                JOptionPane.showMessageDialog(null, "مقدار انتخاب شده با برچسب انتخاب شده سازگار نیست.", "خطا", JOptionPane.ERROR_MESSAGE);
            else{
                valueScrollPane.reloadValues(attachedLabel.getValues());
                labelValueTextField.setText("");
            }
        } catch (DuplicatedValueException ex) {
            JOptionPane.showMessageDialog(null, "مقدار انتخاب شده تکراری است.", "خطا", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addValueButtonActionPerformed

    private void attachLabelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachLabelButtonActionPerformed
        Label label = (Label)labelScrollPane.getSelectedItem();
        Asset asset = (Asset)assetScrollPane.getSelectedItem();
        if(label == null){
            JOptionPane.showMessageDialog(null, "برچسبی انتخاب نشده است.", "خطا", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(asset == null){
            JOptionPane.showMessageDialog(null, "دارایی انتخاب نشده است.", "خطا", JOptionPane.ERROR_MESSAGE);
            return;
        }
        attachedLabel.setAsset(asset);
        asset.attachLable(attachedLabel);
        JOptionPane.showMessageDialog(null, "برچسب با موفقیت الصاق شد.", "", JOptionPane.INFORMATION_MESSAGE);
        
        //clear
        labelValueTextField.setText("");
        assetScrollPane.deSelect();
        labelScrollPane.deSelect();
        attachedLabel = new AttachedLabel();
        valueScrollPane.reloadValues(attachedLabel.getValues());
        hintPane.setText("هنوز برچسی انتخاب نشده است.");
        StyledDocument doc = hintPane.getStyledDocument();
        SimpleAttributeSet right = new SimpleAttributeSet();
        StyleConstants.setAlignment(right, StyleConstants.ALIGN_RIGHT);
        doc.setParagraphAttributes(0, doc.getLength(), right, false);
        hintPane.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }//GEN-LAST:event_attachLabelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AssetAttachLabelFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addValueButton;
    private javax.swing.JTabbedPane attachAssetLabel;
    private javax.swing.JButton attachLabelButton;
    private javax.swing.JPanel chooseAsset;
    private javax.swing.JPanel chooseLabel;
    private javax.swing.JPanel chooseValue;
    private javax.swing.JTextPane hintPane;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField labelValueTextField;
    // End of variables declaration//GEN-END:variables
}
