/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Nov 29, 2013, 2:04:52 PM
 */
package GUI.event;

import GUI.utility.ScrollableListPanel;
import event.Event;
import event.EventCatalogue;
import exceptions.DuplicatedValueException;
import java.awt.ComponentOrientation;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import label.Label;
import operation.Operation;
import operation.OperationCatalogue;

/**
 *
 * @author Bagher
 */
public class NewEventFrame extends javax.swing.JFrame {
    
    private EventManagementFrame eventManagementFrame;
    private ScrollableListPanel valueScrollPane;
    private Event event;

    /** Creates new form MainFrame */
    public NewEventFrame(EventManagementFrame eventManagementFrame) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e) {
          System.out.println("Error setting native LAF: " + e);
        }
        this.eventManagementFrame = eventManagementFrame;
        
        initComponents();
        operations.setModel(new JComboBox<>(OperationCatalogue.getInstace().getOperations().toArray(new Operation[0])).getModel());
        Operation operation = (Operation) operations.getSelectedItem();
        event = new Event(operation);
        
        valueScrollPane = new ScrollableListPanel("مقدار برچسب", false);
        valueScrollPane.reloadValues(event.getValues());
        this.add(valueScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 270, 190));
        loadMyComponents();
    }
    
    private void loadMyComponents(){
        Operation operation = (Operation) operations.getSelectedItem();
        assetNameLabel.setText(operation.getAsset().getName());
        labelNameLabel.setText(operation.getAttachedLabel().getLabel().getName());
        labelvaluelabel.setText(operation.getAttachedLabel().getHumanReadableValues());
        Label label = operation.getAttachedLabel().getLabel();
        if(label != null){
            Object[] objects = label.getValues();
            String hint = "";
            for(Object object: objects)
                hint += "• " + object.toString() + "\n";
            hintPane.setText(hint);
            if(label.getType().getTypeName().equals("String")){
                StyledDocument doc = hintPane.getStyledDocument();
                SimpleAttributeSet right = new SimpleAttributeSet();
                StyleConstants.setAlignment(right, StyleConstants.ALIGN_RIGHT);
                doc.setParagraphAttributes(0, doc.getLength(), right, false);
                hintPane.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
            }else{
                StyledDocument doc = hintPane.getStyledDocument();
                SimpleAttributeSet right = new SimpleAttributeSet();
                StyleConstants.setAlignment(right, StyleConstants.ALIGN_LEFT);
                doc.setParagraphAttributes(0, doc.getLength(), right, false);
                hintPane.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
            }
        }
        if(event.getOperation() != operation){
            event = new Event(operation);
            valueScrollPane.reloadValues(event.getValues());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        eventName = new javax.swing.JTextField();
        operations = new javax.swing.JComboBox();
        jLabel51 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        assetNameLabel = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        labelNameLabel = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        labelvaluelabel = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hintPane = new javax.swing.JTextPane();
        labelValueTextField = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        addValueButton = new javax.swing.JButton();
        attachLabelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("سامانه‌ی مدیریت ‍پیکربندی شهردای");
        setBackground(new java.awt.Color(152, 152, 152));
        setBounds(new java.awt.Rectangle(50, 50, 750, 500));
        setMinimumSize(new java.awt.Dimension(750, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Web Yekan", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("تعریف رخداد جدید");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 431, -1));

        jLabel50.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel50.setText("نام رخداد:");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 105, 34));

        eventName.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        eventName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(eventName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 170, -1));

        operations.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        operations.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "عملیات مربوط به آتش", "خطکشی خیابان رودکی", "آبیاری پارک لاله", "عملیات مربوط به سیل", "عملیات مربوط به زلزله" }));
        operations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationsActionPerformed(evt);
            }
        });
        getContentPane().add(operations, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 170, -1));

        jLabel51.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel51.setText("عملیات مربوطه:");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 110, 34));

        jLabel56.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel56.setText("نام دارایی:");
        jLabel56.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 70, -1));

        assetNameLabel.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        assetNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        assetNameLabel.setText("نام دارایی");
        assetNameLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(assetNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 150, -1));

        jLabel52.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel52.setText("نام برچسب:");
        jLabel52.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 70, -1));

        labelNameLabel.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        labelNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNameLabel.setText("نام برچسب");
        labelNameLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(labelNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 150, -1));

        jLabel54.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel54.setText("مقدار فعلی برچسب:");
        jLabel54.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 150, -1));

        labelvaluelabel.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        labelvaluelabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelvaluelabel.setText("مقدار فعلی");
        labelvaluelabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(labelvaluelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 150, -1));

        jLabel53.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel53.setText("مقادیر ممکن برچسب");
        jLabel53.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 150, -1));

        hintPane.setFont(new java.awt.Font("XB Zar", 0, 15)); // NOI18N
        hintPane.setText("هنوز برچسی انتخاب نشده است.");
        jScrollPane2.setViewportView(hintPane);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 210, 290));

        labelValueTextField.setFont(new java.awt.Font("XB Zar", 0, 15)); // NOI18N
        labelValueTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(labelValueTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 170, -1));

        jLabel55.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel55.setText("مجموعه مقادیر  بعداز اعمال رخداد");
        getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 200, -1));

        addValueButton.setBackground(new java.awt.Color(60, 0, 91));
        addValueButton.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        addValueButton.setForeground(new java.awt.Color(1, 1, 1));
        addValueButton.setText("اضافه‌کردن");
        addValueButton.setFocusPainted(false);
        addValueButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        addValueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addValueButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addValueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 90, 30));

        attachLabelButton.setBackground(new java.awt.Color(60, 0, 91));
        attachLabelButton.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        attachLabelButton.setForeground(new java.awt.Color(1, 1, 1));
        attachLabelButton.setText("ذخیره‌ی رخداد");
        attachLabelButton.setFocusPainted(false);
        attachLabelButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        attachLabelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachLabelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(attachLabelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addValueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addValueButtonActionPerformed
        try {
            if(event.addValue(labelValueTextField.getText()) == false)
            JOptionPane.showMessageDialog(null, "مقدار انتخاب شده با برچسب انتخاب شده سازگار نیست.", "خطا", JOptionPane.ERROR_MESSAGE);
            else{
                valueScrollPane.reloadValues(event.getValues());
                labelValueTextField.setText("");
            }
        } catch (DuplicatedValueException ex) {
            JOptionPane.showMessageDialog(null, "مقدار انتخاب شده تکراری است.", "خطا", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addValueButtonActionPerformed

    private void operationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationsActionPerformed
        loadMyComponents();
        
    }//GEN-LAST:event_operationsActionPerformed

    private void attachLabelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachLabelButtonActionPerformed
        EventCatalogue.getInstace().addEvent(event);
        event.setName(eventName.getText());
        eventManagementFrame.loadEventComponents();
        JOptionPane.showMessageDialog(null, "رخداد با موفقیت اضافه شد.", "", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_attachLabelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addValueButton;
    private javax.swing.JLabel assetNameLabel;
    private javax.swing.JButton attachLabelButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField eventName;
    private javax.swing.JTextPane hintPane;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNameLabel;
    private javax.swing.JTextField labelValueTextField;
    private javax.swing.JLabel labelvaluelabel;
    private javax.swing.JComboBox operations;
    private javax.swing.JButton saveOperationButton;
    private javax.swing.JButton saveOperationButton1;
    private javax.swing.JButton saveOperationButton2;
    private javax.swing.JButton saveOperationButton3;
    private javax.swing.JButton saveOperationButton4;
    private javax.swing.JButton saveOperationButton5;
    // End of variables declaration//GEN-END:variables
}
