/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Nov 29, 2013, 2:04:52 PM
 */
package GUI.report;
import GUI.operation.*;


/**
 *
 * @author Bagher
 */
public class Report extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public Report() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jScrollBar2 = new javax.swing.JScrollBar();
        jComboBox5 = new javax.swing.JComboBox();
        jPanel15 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jScrollBar3 = new javax.swing.JScrollBar();
        jPanel21 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollBar1 = new javax.swing.JScrollBar();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel47 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jButton24 = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jScrollBar4 = new javax.swing.JScrollBar();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel72 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jPanel32 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jScrollBar5 = new javax.swing.JScrollBar();
        jPanel33 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jLabel107 = new javax.swing.JLabel();
        jScrollBar6 = new javax.swing.JScrollBar();
        jPanel36 = new javax.swing.JPanel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jLabel126 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel127 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("سامانه‌ی مدیریت ‍پیکربندی شهردای");
        setBounds(new java.awt.Rectangle(50, 50, 750, 500));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(750, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Web Yekan", 0, 24));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("گزارشگیری");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 431, 70));

        jButton23.setBackground(new java.awt.Color(60, 0, 91));
        jButton23.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jButton23.setForeground(new java.awt.Color(1, 1, 1));
        jButton23.setText("خروج");
        jButton23.setFocusPainted(false);
        jButton23.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 30));

        jButton15.setBackground(new java.awt.Color(60, 0, 91));
        jButton15.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jButton15.setForeground(new java.awt.Color(1, 1, 1));
        jButton15.setText("پیش‌خوان");
        jButton15.setFocusPainted(false);
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 90, 30));

        jTabbedPane1.setFont(jComboBox3.getFont());

        jInternalFrame3.getContentPane().setLayout(null);
        jInternalFrame3.getContentPane().add(jScrollBar2);
        jScrollBar2.setBounds(700, 80, 17, 190);

        jComboBox5.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "دوربین  ۱۲۲۰", "خیابان آزادی", "خیابان شفا", "خیابان ولیعصر", "میدان آزادی " }));
        jInternalFrame3.getContentPane().add(jComboBox5);
        jComboBox5.setBounds(200, 20, 120, 30);

        jPanel15.setBackground(new java.awt.Color(205, 205, 205));
        jPanel15.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("سر چهارراه منتهی به خونه");
        jPanel15.add(jLabel35);
        jLabel35.setBounds(230, 0, 150, 30);

        jLabel57.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel57.setText("مکان");
        jPanel15.add(jLabel57);
        jLabel57.setBounds(470, 0, 200, 30);

        jInternalFrame3.getContentPane().add(jPanel15);
        jPanel15.setBounds(20, 150, 680, 30);

        jPanel16.setBackground(new java.awt.Color(254, 254, 254));
        jPanel16.setLayout(null);

        jLabel38.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("خراب یا خاموش");
        jPanel16.add(jLabel38);
        jLabel38.setBounds(270, 0, 110, 30);

        jLabel58.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel58.setText("حالت");
        jPanel16.add(jLabel58);
        jLabel58.setBounds(470, 0, 200, 30);

        jInternalFrame3.getContentPane().add(jPanel16);
        jPanel16.setBounds(20, 120, 680, 30);

        jPanel17.setBackground(new java.awt.Color(160, 196, 255));
        jPanel17.setLayout(null);

        jLabel41.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("موضوع");
        jPanel17.add(jLabel41);
        jLabel41.setBounds(610, 0, 60, 40);

        jLabel42.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel42.setText("شرح");
        jPanel17.add(jLabel42);
        jLabel42.setBounds(290, 0, 90, 40);

        jInternalFrame3.getContentPane().add(jPanel17);
        jPanel17.setBounds(20, 80, 680, 40);

        jPanel18.setBackground(new java.awt.Color(205, 205, 205));
        jPanel18.setLayout(null);

        jLabel45.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel45.setText("نوع");
        jPanel18.add(jLabel45);
        jLabel45.setBounds(480, 0, 190, 30);

        jLabel59.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel59.setText("ساده");
        jPanel18.add(jLabel59);
        jLabel59.setBounds(340, 0, 40, 30);

        jInternalFrame3.getContentPane().add(jPanel18);
        jPanel18.setBounds(20, 210, 680, 30);

        jPanel19.setBackground(new java.awt.Color(254, 254, 254));
        jPanel19.setLayout(null);

        jLabel60.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel60.setText("ندارد");
        jPanel19.add(jLabel60);
        jLabel60.setBounds(320, 0, 60, 30);

        jLabel61.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel61.setText("زیردارایی");
        jPanel19.add(jLabel61);
        jLabel61.setBounds(470, 0, 200, 30);

        jInternalFrame3.getContentPane().add(jPanel19);
        jPanel19.setBounds(20, 240, 680, 30);

        jPanel20.setBackground(new java.awt.Color(254, 254, 254));
        jPanel20.setLayout(null);

        jLabel62.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel62.setText("۱۵۷");
        jPanel20.add(jLabel62);
        jLabel62.setBounds(320, 0, 60, 30);

        jLabel63.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel63.setText("UID");
        jPanel20.add(jLabel63);
        jLabel63.setBounds(590, 90, 30, 30);

        jLabel65.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel65.setText("UID");
        jPanel20.add(jLabel65);
        jLabel65.setBounds(590, 90, 30, 30);

        jLabel66.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel66.setText("UID");
        jPanel20.add(jLabel66);
        jLabel66.setBounds(640, 0, 30, 30);

        jInternalFrame3.getContentPane().add(jPanel20);
        jPanel20.setBounds(20, 180, 680, 30);

        jButton25.setBackground(new java.awt.Color(60, 0, 91));
        jButton25.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jButton25.setForeground(new java.awt.Color(1, 1, 1));
        jButton25.setText("نمایش گزارش");
        jButton25.setFocusPainted(false);
        jButton25.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(jButton25);
        jButton25.setBounds(20, 20, 110, 32);

        jTextField1.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("157");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(jTextField1);
        jTextField1.setBounds(380, 20, 60, 28);

        jLabel64.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel64.setText("تغییرات انجام شده بر دارایی از ابتدا تا لحظه‌ی ایجاد گزارش");
        jInternalFrame3.getContentPane().add(jLabel64);
        jLabel64.setBounds(410, 290, 310, 30);

        jLabel56.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel56.setText("UID");
        jInternalFrame3.getContentPane().add(jLabel56);
        jLabel56.setBounds(470, 20, 30, 30);
        jInternalFrame3.getContentPane().add(jScrollBar3);
        jScrollBar3.setBounds(700, 330, 17, 160);

        jPanel21.setBackground(new java.awt.Color(205, 205, 205));
        jPanel21.setLayout(null);

        jLabel67.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel67.setText("تعمیر دوربین ۱۲۲۰");
        jPanel21.add(jLabel67);
        jLabel67.setBounds(470, 0, 200, 30);

        jLabel43.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel43.setText("تغییر حالت از خراب به روشن");
        jPanel21.add(jLabel43);
        jLabel43.setBounds(220, 0, 160, 30);

        jLabel104.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel104.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel104.setText("۱۳۹۲/۸/۰۲");
        jPanel21.add(jLabel104);
        jLabel104.setBounds(20, 0, 80, 30);

        jInternalFrame3.getContentPane().add(jPanel21);
        jPanel21.setBounds(20, 400, 680, 30);

        jPanel22.setBackground(new java.awt.Color(254, 254, 254));
        jPanel22.setLayout(null);

        jLabel68.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel68.setText("تعمیر دوربین ۱۲۲۰");
        jPanel22.add(jLabel68);
        jLabel68.setBounds(470, 0, 200, 30);

        jLabel99.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel99.setText("۱۳۹۲/۹/۱۲");
        jPanel22.add(jLabel99);
        jLabel99.setBounds(20, 0, 80, 30);

        jLabel36.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("تغییر حالت از خاموش به روشن");
        jPanel22.add(jLabel36);
        jLabel36.setBounds(200, 0, 180, 30);

        jInternalFrame3.getContentPane().add(jPanel22);
        jPanel22.setBounds(20, 370, 680, 30);

        jPanel23.setBackground(new java.awt.Color(160, 196, 255));
        jPanel23.setLayout(null);

        jLabel48.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel48.setText("موضوع تغییر");
        jPanel23.add(jLabel48);
        jLabel48.setBounds(580, 0, 90, 40);

        jLabel49.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel49.setText("تاریخ");
        jPanel23.add(jLabel49);
        jLabel49.setBounds(50, 0, 50, 40);

        jLabel98.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel98.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel98.setText("شرح");
        jPanel23.add(jLabel98);
        jLabel98.setBounds(290, 0, 90, 40);

        jInternalFrame3.getContentPane().add(jPanel23);
        jPanel23.setBounds(20, 330, 680, 40);

        jPanel24.setBackground(new java.awt.Color(205, 205, 205));
        jPanel24.setLayout(null);

        jLabel69.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel69.setText("نصب دوربین");
        jPanel24.add(jLabel69);
        jLabel69.setBounds(480, 0, 190, 30);

        jLabel70.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel70.setText("تغییر حالت دوربین از خاموش به روشن");
        jPanel24.add(jLabel70);
        jLabel70.setBounds(150, 0, 230, 30);

        jLabel106.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel106.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel106.setText("۱۳۹۲/۵/۲۲");
        jPanel24.add(jLabel106);
        jLabel106.setBounds(20, 0, 80, 30);

        jInternalFrame3.getContentPane().add(jPanel24);
        jPanel24.setBounds(20, 460, 680, 30);

        jPanel26.setBackground(new java.awt.Color(254, 254, 254));
        jPanel26.setLayout(null);

        jLabel74.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel74.setText("UID");
        jPanel26.add(jLabel74);
        jLabel74.setBounds(590, 90, 30, 30);

        jLabel75.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel75.setText("UID");
        jPanel26.add(jLabel75);
        jLabel75.setBounds(590, 90, 30, 30);

        jLabel76.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel76.setText("سرویس دوربین ۱۲۲۰");
        jPanel26.add(jLabel76);
        jLabel76.setBounds(470, 0, 200, 30);

        jLabel71.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel71.setText("تغییر حالت از سرویس نشده به سرویس شده");
        jPanel26.add(jLabel71);
        jLabel71.setBounds(130, 0, 250, 30);

        jLabel105.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel105.setText("۱۳۹۲/۷/۱۱");
        jPanel26.add(jLabel105);
        jLabel105.setBounds(20, 0, 80, 30);

        jInternalFrame3.getContentPane().add(jPanel26);
        jPanel26.setBounds(20, 430, 680, 30);

        jLabel77.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel77.setText("دارایی مورد نظر را انتخاب کنید");
        jInternalFrame3.getContentPane().add(jLabel77);
        jLabel77.setBounds(550, 20, 170, 30);

        jTabbedPane1.addTab("برحسب یک دارایی", jInternalFrame3);

        jInternalFrame1.getContentPane().setLayout(null);
        jInternalFrame1.getContentPane().add(jScrollBar1);
        jScrollBar1.setBounds(700, 80, 17, 190);

        jComboBox3.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "خیابان", "خطکشی", "دوربین", "پارک", "لوله‌کشی", "پارک" }));
        jInternalFrame1.getContentPane().add(jComboBox3);
        jComboBox3.setBounds(390, 20, 100, 30);

        jLabel47.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel47.setText("برچسب مورد نظر را انتخاب کنید");
        jInternalFrame1.getContentPane().add(jLabel47);
        jLabel47.setBounds(550, 20, 170, 30);

        jPanel9.setBackground(new java.awt.Color(205, 205, 205));
        jPanel9.setLayout(null);

        jLabel34.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("ساده");
        jPanel9.add(jLabel34);
        jLabel34.setBounds(320, 0, 60, 30);

        jLabel50.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel50.setText("نوع دارایی");
        jPanel9.add(jLabel50);
        jLabel50.setBounds(470, 0, 200, 30);

        jInternalFrame1.getContentPane().add(jPanel9);
        jPanel9.setBounds(20, 150, 680, 30);

        jPanel10.setBackground(new java.awt.Color(254, 254, 254));
        jPanel10.setLayout(null);

        jLabel37.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("۱۱۲");
        jPanel10.add(jLabel37);
        jLabel37.setBounds(320, 0, 60, 30);

        jLabel46.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel46.setText("تعداد دارایی با برچسب خطکشی");
        jPanel10.add(jLabel46);
        jLabel46.setBounds(470, 0, 200, 30);

        jInternalFrame1.getContentPane().add(jPanel10);
        jPanel10.setBounds(20, 120, 680, 30);

        jPanel11.setBackground(new java.awt.Color(160, 196, 255));
        jPanel11.setLayout(null);

        jLabel39.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("موضوع");
        jPanel11.add(jLabel39);
        jLabel39.setBounds(610, 0, 60, 40);

        jLabel40.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("شرح");
        jPanel11.add(jLabel40);
        jLabel40.setBounds(290, 0, 90, 40);

        jInternalFrame1.getContentPane().add(jPanel11);
        jPanel11.setBounds(20, 80, 680, 40);

        jPanel12.setBackground(new java.awt.Color(205, 205, 205));
        jPanel12.setLayout(null);

        jLabel44.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel44.setText("تعداد دارایی با حالت خطکشی شده");
        jPanel12.add(jLabel44);
        jLabel44.setBounds(480, 0, 190, 30);

        jLabel51.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel51.setText("۵۸");
        jPanel12.add(jLabel51);
        jLabel51.setBounds(340, 0, 40, 30);

        jInternalFrame1.getContentPane().add(jPanel12);
        jPanel12.setBounds(20, 210, 680, 30);

        jPanel13.setBackground(new java.awt.Color(254, 254, 254));
        jPanel13.setLayout(null);

        jLabel54.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel54.setText("۴۹");
        jPanel13.add(jLabel54);
        jLabel54.setBounds(320, 0, 60, 30);

        jLabel52.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel52.setText("تعداد دارایی باحالات خطکشی کم رنگ");
        jPanel13.add(jLabel52);
        jLabel52.setBounds(470, 0, 200, 30);

        jInternalFrame1.getContentPane().add(jPanel13);
        jPanel13.setBounds(20, 240, 680, 30);

        jPanel14.setBackground(new java.awt.Color(254, 254, 254));
        jPanel14.setLayout(null);

        jLabel55.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel55.setText("ندارد");
        jPanel14.add(jLabel55);
        jLabel55.setBounds(320, 0, 60, 30);

        jLabel53.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel53.setText("زیر برچسب");
        jPanel14.add(jLabel53);
        jLabel53.setBounds(570, 0, 100, 30);

        jInternalFrame1.getContentPane().add(jPanel14);
        jPanel14.setBounds(20, 180, 680, 30);

        jButton24.setBackground(new java.awt.Color(60, 0, 91));
        jButton24.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jButton24.setForeground(new java.awt.Color(1, 1, 1));
        jButton24.setText("نمایش گزارش");
        jButton24.setFocusPainted(false);
        jButton24.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton24);
        jButton24.setBounds(20, 20, 110, 32);

        jTabbedPane1.addTab("برحسب برچسب خاص", jInternalFrame1);

        jInternalFrame2.getContentPane().setLayout(null);
        jInternalFrame2.getContentPane().add(jScrollBar4);
        jScrollBar4.setBounds(700, 80, 17, 220);

        jComboBox4.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "لوله کشی گاز خیابان شفا", "تعمیر دوربین شماره ۱۲۲۰", "خطکشی خیابان آزادی", "..." }));
        jInternalFrame2.getContentPane().add(jComboBox4);
        jComboBox4.setBounds(330, 20, 160, 30);

        jLabel72.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel72.setText("عملیات مورد نظر را انتخاب کنید");
        jInternalFrame2.getContentPane().add(jLabel72);
        jLabel72.setBounds(550, 20, 170, 30);

        jPanel25.setBackground(new java.awt.Color(205, 205, 205));
        jPanel25.setLayout(null);

        jLabel73.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel73.setText("۳");
        jPanel25.add(jLabel73);
        jLabel73.setBounds(330, 0, 60, 30);

        jLabel78.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel78.setText("تعداد زیر عملیات");
        jPanel25.add(jLabel78);
        jLabel78.setBounds(470, 0, 200, 30);

        jInternalFrame2.getContentPane().add(jPanel25);
        jPanel25.setBounds(20, 150, 680, 30);

        jPanel27.setBackground(new java.awt.Color(254, 254, 254));
        jPanel27.setLayout(null);

        jLabel80.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel80.setText("نوع عملیات");
        jPanel27.add(jLabel80);
        jLabel80.setBounds(610, 0, 60, 30);

        jLabel90.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel90.setText("مرکب");
        jPanel27.add(jLabel90);
        jLabel90.setBounds(330, 0, 60, 30);

        jInternalFrame2.getContentPane().add(jPanel27);
        jPanel27.setBounds(20, 120, 680, 30);

        jPanel28.setBackground(new java.awt.Color(160, 196, 255));
        jPanel28.setLayout(null);

        jLabel81.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel81.setText("موضوع");
        jPanel28.add(jLabel81);
        jLabel81.setBounds(610, 0, 60, 40);

        jLabel89.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel89.setText("شرح");
        jPanel28.add(jLabel89);
        jLabel89.setBounds(360, 0, 30, 40);

        jInternalFrame2.getContentPane().add(jPanel28);
        jPanel28.setBounds(20, 80, 680, 40);

        jPanel29.setBackground(new java.awt.Color(205, 205, 205));
        jPanel29.setLayout(null);

        jLabel83.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel83.setText("تاریخ پایان عملیات");
        jPanel29.add(jLabel83);
        jLabel83.setBounds(480, 0, 190, 30);

        jLabel84.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel84.setText("۱۳۹۲/۶/۰۱");
        jPanel29.add(jLabel84);
        jLabel84.setBounds(310, 0, 80, 30);

        jInternalFrame2.getContentPane().add(jPanel29);
        jPanel29.setBounds(20, 270, 680, 30);

        jPanel30.setBackground(new java.awt.Color(254, 254, 254));
        jPanel30.setLayout(null);

        jLabel85.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel85.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel85.setText("۱۳۹۲/۵/۱۲");
        jPanel30.add(jLabel85);
        jLabel85.setBounds(310, 0, 80, 30);

        jLabel86.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel86.setText("تاریخ شروع عملیات");
        jPanel30.add(jLabel86);
        jLabel86.setBounds(470, 0, 200, 30);

        jInternalFrame2.getContentPane().add(jPanel30);
        jPanel30.setBounds(20, 240, 680, 30);

        jPanel31.setBackground(new java.awt.Color(254, 254, 254));
        jPanel31.setLayout(null);

        jLabel87.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel87.setText("۱");
        jPanel31.add(jLabel87);
        jLabel87.setBounds(330, 0, 60, 30);

        jLabel88.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel88.setText("تعداد تکرار");
        jPanel31.add(jLabel88);
        jLabel88.setBounds(570, 0, 100, 30);

        jInternalFrame2.getContentPane().add(jPanel31);
        jPanel31.setBounds(20, 180, 680, 30);

        jButton26.setBackground(new java.awt.Color(60, 0, 91));
        jButton26.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jButton26.setForeground(new java.awt.Color(1, 1, 1));
        jButton26.setText("نمایش گزارش");
        jButton26.setFocusPainted(false);
        jButton26.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton26);
        jButton26.setBounds(20, 20, 110, 32);

        jPanel32.setBackground(new java.awt.Color(205, 205, 205));
        jPanel32.setLayout(null);

        jLabel91.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel91.setText("دارایی‌های تحت عملیات");
        jPanel32.add(jLabel91);
        jLabel91.setBounds(480, 0, 190, 30);

        jLabel92.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel92.setText("خیابان شفا");
        jPanel32.add(jLabel92);
        jLabel92.setBounds(330, 0, 60, 30);

        jInternalFrame2.getContentPane().add(jPanel32);
        jPanel32.setBounds(20, 210, 680, 30);

        jLabel79.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel79.setText("شرح عملیات");
        jInternalFrame2.getContentPane().add(jLabel79);
        jLabel79.setBounds(410, 320, 310, 30);
        jInternalFrame2.getContentPane().add(jScrollBar5);
        jScrollBar5.setBounds(700, 360, 17, 130);

        jPanel33.setBackground(new java.awt.Color(205, 205, 205));
        jPanel33.setLayout(null);

        jLabel82.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel82.setText("تغییر حالت «خیابان شفا» از «بدون لوله‌ی گاز» به «با لوله‌ی گاز»ا");
        jPanel33.add(jLabel82);
        jLabel82.setBounds(52, 0, 328, 30);

        jLabel93.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel93.setText("لوله گذاری در خیابان شفا");
        jPanel33.add(jLabel93);
        jLabel93.setBounds(470, 0, 200, 30);

        jInternalFrame2.getContentPane().add(jPanel33);
        jPanel33.setBounds(20, 430, 680, 30);

        jPanel34.setBackground(new java.awt.Color(254, 254, 254));
        jPanel34.setLayout(null);

        jLabel94.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel94.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel94.setText("تغییر حالت «خیابان شفا» از «آسفالته» به «خاکی»ا");
        jPanel34.add(jLabel94);
        jLabel94.setBounds(120, 0, 260, 30);

        jLabel95.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel95.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel95.setText("کندن خیابان شفا");
        jPanel34.add(jLabel95);
        jLabel95.setBounds(470, 0, 200, 30);

        jInternalFrame2.getContentPane().add(jPanel34);
        jPanel34.setBounds(20, 400, 680, 30);

        jPanel35.setBackground(new java.awt.Color(160, 196, 255));
        jPanel35.setLayout(null);

        jLabel96.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel96.setText("زیر عملیات");
        jPanel35.add(jLabel96);
        jLabel96.setBounds(580, 0, 90, 40);

        jLabel97.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel97.setText("شرح");
        jPanel35.add(jLabel97);
        jLabel97.setBounds(290, 0, 90, 40);

        jInternalFrame2.getContentPane().add(jPanel35);
        jPanel35.setBounds(20, 360, 680, 40);

        jPanel37.setBackground(new java.awt.Color(254, 254, 254));
        jPanel37.setLayout(null);

        jLabel100.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel100.setText("UID");
        jPanel37.add(jLabel100);
        jLabel100.setBounds(590, 90, 30, 30);

        jLabel101.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel101.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel101.setText("UID");
        jPanel37.add(jLabel101);
        jLabel101.setBounds(590, 90, 30, 30);

        jLabel102.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel102.setText("آسفالت خیابان شفا");
        jPanel37.add(jLabel102);
        jLabel102.setBounds(470, 0, 200, 30);

        jLabel103.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel103.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel103.setText("تغییر حالت از «خیابان شفا» از «خاکی» به «آسفالته»ا");
        jPanel37.add(jLabel103);
        jLabel103.setBounds(100, 0, 280, 30);

        jInternalFrame2.getContentPane().add(jPanel37);
        jPanel37.setBounds(20, 460, 680, 30);

        jTabbedPane1.addTab("برحسب عمل خاص", jInternalFrame2);

        jInternalFrame4.getContentPane().setLayout(null);

        jLabel107.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel107.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel107.setText("تغییرات انجام شده بر دارایی از ابتدا تا لحظه‌ی ایجاد گزارش");
        jInternalFrame4.getContentPane().add(jLabel107);
        jLabel107.setBounds(420, 90, 310, 30);
        jInternalFrame4.getContentPane().add(jScrollBar6);
        jScrollBar6.setBounds(710, 130, 17, 280);

        jPanel36.setBackground(new java.awt.Color(205, 205, 205));
        jPanel36.setLayout(null);

        jLabel108.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel108.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel108.setText("تعمیر دوربین ۱۲۲۰");
        jPanel36.add(jLabel108);
        jLabel108.setBounds(470, 0, 200, 30);

        jLabel109.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel109.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel109.setText("تغییر حالت از خراب به روشن");
        jPanel36.add(jLabel109);
        jLabel109.setBounds(220, 0, 160, 30);

        jLabel110.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel110.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel110.setText("۱۳۹۲/۸/۰۲");
        jPanel36.add(jLabel110);
        jLabel110.setBounds(20, 0, 80, 30);

        jInternalFrame4.getContentPane().add(jPanel36);
        jPanel36.setBounds(30, 200, 680, 30);

        jPanel38.setBackground(new java.awt.Color(254, 254, 254));
        jPanel38.setLayout(null);

        jLabel111.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel111.setText("تعمیر دوربین ۱۲۲۰");
        jPanel38.add(jLabel111);
        jLabel111.setBounds(470, 0, 200, 30);

        jLabel112.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel112.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel112.setText("۱۳۹۲/۹/۱۲");
        jPanel38.add(jLabel112);
        jLabel112.setBounds(20, 0, 80, 30);

        jLabel113.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel113.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel113.setText("تغییر حالت از خاموش به روشن");
        jPanel38.add(jLabel113);
        jLabel113.setBounds(200, 0, 180, 30);

        jInternalFrame4.getContentPane().add(jPanel38);
        jPanel38.setBounds(30, 170, 680, 30);

        jPanel39.setBackground(new java.awt.Color(160, 196, 255));
        jPanel39.setLayout(null);

        jLabel114.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel114.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel114.setText("موضوع تغییر");
        jPanel39.add(jLabel114);
        jLabel114.setBounds(580, 0, 90, 40);

        jLabel115.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel115.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel115.setText("تاریخ");
        jPanel39.add(jLabel115);
        jLabel115.setBounds(50, 0, 50, 40);

        jLabel116.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel116.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel116.setText("شرح");
        jPanel39.add(jLabel116);
        jLabel116.setBounds(290, 0, 90, 40);

        jInternalFrame4.getContentPane().add(jPanel39);
        jPanel39.setBounds(30, 130, 680, 40);

        jPanel40.setBackground(new java.awt.Color(205, 205, 205));
        jPanel40.setLayout(null);

        jLabel117.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel117.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel117.setText("نصب دوربین");
        jPanel40.add(jLabel117);
        jLabel117.setBounds(480, 0, 190, 30);

        jLabel118.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel118.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel118.setText("تغییر حالت دوربین از خاموش به روشن");
        jPanel40.add(jLabel118);
        jLabel118.setBounds(150, 0, 230, 30);

        jLabel119.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel119.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel119.setText("۱۳۹۲/۵/۲۲");
        jPanel40.add(jLabel119);
        jLabel119.setBounds(20, 0, 80, 30);

        jInternalFrame4.getContentPane().add(jPanel40);
        jPanel40.setBounds(30, 260, 680, 30);

        jPanel41.setBackground(new java.awt.Color(254, 254, 254));
        jPanel41.setLayout(null);

        jLabel120.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel120.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel120.setText("UID");
        jPanel41.add(jLabel120);
        jLabel120.setBounds(590, 90, 30, 30);

        jLabel121.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel121.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel121.setText("UID");
        jPanel41.add(jLabel121);
        jLabel121.setBounds(590, 90, 30, 30);

        jLabel122.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel122.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel122.setText("سرویس دوربین ۱۲۲۰");
        jPanel41.add(jLabel122);
        jLabel122.setBounds(470, 0, 200, 30);

        jLabel123.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel123.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel123.setText("تغییر حالت از سرویس نشده به سرویس شده");
        jPanel41.add(jLabel123);
        jLabel123.setBounds(130, 0, 250, 30);

        jLabel124.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel124.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel124.setText("۱۳۹۲/۷/۱۱");
        jPanel41.add(jLabel124);
        jLabel124.setBounds(20, 0, 80, 30);

        jInternalFrame4.getContentPane().add(jPanel41);
        jPanel41.setBounds(30, 230, 680, 30);

        jButton27.setBackground(new java.awt.Color(60, 0, 91));
        jButton27.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jButton27.setForeground(new java.awt.Color(1, 1, 1));
        jButton27.setText("نمایش گزارش");
        jButton27.setFocusPainted(false);
        jButton27.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jButton27);
        jButton27.setBounds(20, 20, 110, 32);

        jLabel126.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel126.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel126.setText("بازه زمانی مورد نظر را انتخاب کنید");
        jInternalFrame4.getContentPane().add(jLabel126);
        jLabel126.setBounds(540, 20, 180, 30);

        jLabel125.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel125.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel125.setText("از");
        jInternalFrame4.getContentPane().add(jLabel125);
        jLabel125.setBounds(480, 20, 10, 30);

        jTextField2.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("۱۳۹۲/۹/۱۲");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField2);
        jTextField2.setBounds(260, 20, 90, 28);

        jTextField3.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText("۱۳۹۲/۲/۱۲");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField3);
        jTextField3.setBounds(380, 20, 90, 28);

        jLabel127.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel127.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel127.setText("تا");
        jInternalFrame4.getContentPane().add(jLabel127);
        jLabel127.setBounds(360, 20, 10, 30);

        jPanel42.setBackground(new java.awt.Color(205, 205, 205));
        jPanel42.setLayout(null);

        jLabel128.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel128.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel128.setText("تعمیر دوربین ۱۲۲۰");
        jPanel42.add(jLabel128);
        jLabel128.setBounds(470, 0, 200, 30);

        jLabel129.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel129.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel129.setText("تغییر حالت از خراب به روشن");
        jPanel42.add(jLabel129);
        jLabel129.setBounds(220, 0, 160, 30);

        jLabel130.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel130.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel130.setText("۱۳۹۲/۸/۰۲");
        jPanel42.add(jLabel130);
        jLabel130.setBounds(20, 0, 80, 30);

        jInternalFrame4.getContentPane().add(jPanel42);
        jPanel42.setBounds(30, 320, 680, 30);

        jPanel43.setBackground(new java.awt.Color(254, 254, 254));
        jPanel43.setLayout(null);

        jLabel131.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel131.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel131.setText("تعمیر دوربین ۱۲۲۰");
        jPanel43.add(jLabel131);
        jLabel131.setBounds(470, 0, 200, 30);

        jLabel132.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel132.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel132.setText("۱۳۹۲/۹/۱۲");
        jPanel43.add(jLabel132);
        jLabel132.setBounds(20, 0, 80, 30);

        jLabel133.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel133.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel133.setText("تغییر حالت از خاموش به روشن");
        jPanel43.add(jLabel133);
        jLabel133.setBounds(200, 0, 180, 30);

        jInternalFrame4.getContentPane().add(jPanel43);
        jPanel43.setBounds(30, 290, 680, 30);

        jPanel44.setBackground(new java.awt.Color(205, 205, 205));
        jPanel44.setLayout(null);

        jLabel134.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel134.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel134.setText("نصب دوربین");
        jPanel44.add(jLabel134);
        jLabel134.setBounds(480, 0, 190, 30);

        jLabel135.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel135.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel135.setText("تغییر حالت دوربین از خاموش به روشن");
        jPanel44.add(jLabel135);
        jLabel135.setBounds(150, 0, 230, 30);

        jLabel136.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel136.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel136.setText("۱۳۹۲/۵/۲۲");
        jPanel44.add(jLabel136);
        jLabel136.setBounds(20, 0, 80, 30);

        jInternalFrame4.getContentPane().add(jPanel44);
        jPanel44.setBounds(30, 380, 680, 30);

        jPanel45.setBackground(new java.awt.Color(254, 254, 254));
        jPanel45.setLayout(null);

        jLabel137.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel137.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel137.setText("UID");
        jPanel45.add(jLabel137);
        jLabel137.setBounds(590, 90, 30, 30);

        jLabel138.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel138.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel138.setText("UID");
        jPanel45.add(jLabel138);
        jLabel138.setBounds(590, 90, 30, 30);

        jLabel139.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel139.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel139.setText("سرویس دوربین ۱۲۲۰");
        jPanel45.add(jLabel139);
        jLabel139.setBounds(470, 0, 200, 30);

        jLabel140.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel140.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel140.setText("تغییر حالت از سرویس نشده به سرویس شده");
        jPanel45.add(jLabel140);
        jLabel140.setBounds(130, 0, 250, 30);

        jLabel141.setFont(new java.awt.Font("Web Yekan", 0, 15));
        jLabel141.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel141.setText("۱۳۹۲/۷/۱۱");
        jPanel45.add(jLabel141);
        jLabel141.setBounds(20, 0, 80, 30);

        jInternalFrame4.getContentPane().add(jPanel45);
        jPanel45.setBounds(30, 350, 680, 30);

        jTabbedPane1.addTab("سری زمانی", jInternalFrame4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 760, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton23ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Report().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollBar jScrollBar3;
    private javax.swing.JScrollBar jScrollBar4;
    private javax.swing.JScrollBar jScrollBar5;
    private javax.swing.JScrollBar jScrollBar6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
