/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.asset.newAsset;

/**
 *
 * @author bagher
 */
public class NewAssetFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewAssetFrame
     */
    public NewAssetFrame() {
        initComponents();
        newAssetFrame.setEnabledAt(1, false);
        newAssetFrame.setEnabledAt(2, false);
        newAssetFrame.setEnabledAt(3, false);
        newAssetFrame.setEnabledAt(4, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        newAssetFrame = new javax.swing.JTabbedPane();
        primaryTab = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        assetName = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        assetUID = new javax.swing.JTextField();
        isComposite = new javax.swing.JCheckBox();
        hasPlace = new javax.swing.JCheckBox();
        isHuman = new javax.swing.JCheckBox();
        isPhysical = new javax.swing.JCheckBox();
        subAssetTab = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        assetsScrollPane = new javax.swing.JScrollPane();
        assetsPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton34 = new javax.swing.JButton();
        humanTab = new javax.swing.JInternalFrame();
        jLabel7 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        placeTab = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        physicalTab = new javax.swing.JInternalFrame();
        jLabel62 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel63 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        finalTab = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        finalAssetName = new javax.swing.JLabel();
        finalAssetUID = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        finalAssetName1 = new javax.swing.JLabel();
        finalAssetName2 = new javax.swing.JLabel();
        finalAssetName3 = new javax.swing.JLabel();
        finalAssetName4 = new javax.swing.JLabel();
        jButton35 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        primaryTab.setVisible(true);

        jLabel3.setFont(new java.awt.Font("Web Yekan", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("تعریف دارایی جدید - مشخصات پایه");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        assetName.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        assetName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        assetName.setText("میدان آزادی");
        assetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assetNameActionPerformed(evt);
            }
        });
        assetName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                assetNameFocusLost(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel51.setText("نام دارایی");

        jLabel47.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel47.setText("UID");

        assetUID.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        assetUID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        assetUID.setText("azadi.squar.371");
        assetUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assetUIDActionPerformed(evt);
            }
        });
        assetUID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                assetUIDFocusLost(evt);
            }
        });

        isComposite.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        isComposite.setText("دارایی مرکب است");
        isComposite.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        isComposite.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        isComposite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isCompositeActionPerformed(evt);
            }
        });

        hasPlace.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        hasPlace.setText("دارایی مکان‌مند است");
        hasPlace.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hasPlace.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        hasPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasPlaceActionPerformed(evt);
            }
        });

        isHuman.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        isHuman.setText("دارایی انسانی است");
        isHuman.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        isHuman.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        isHuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isHumanActionPerformed(evt);
            }
        });

        isPhysical.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        isPhysical.setText("دارایی فیزیکی (ملموس) است");
        isPhysical.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        isPhysical.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        isPhysical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isPhysicalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout primaryTabLayout = new javax.swing.GroupLayout(primaryTab.getContentPane());
        primaryTab.getContentPane().setLayout(primaryTabLayout);
        primaryTabLayout.setHorizontalGroup(
            primaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primaryTabLayout.createSequentialGroup()
                .addGroup(primaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(primaryTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(primaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isHuman, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isPhysical, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isComposite, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hasPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(primaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(primaryTabLayout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, primaryTabLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(primaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(assetUID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(assetName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(primaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, primaryTabLayout.createSequentialGroup()
                                    .addGap(59, 59, 59)
                                    .addComponent(jLabel51))
                                .addGroup(primaryTabLayout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(jLabel47))))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        primaryTabLayout.setVerticalGroup(
            primaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primaryTabLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(primaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51)
                    .addComponent(assetName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(primaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(assetUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(isComposite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isHuman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hasPlace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isPhysical)
                .addGap(0, 121, Short.MAX_VALUE))
        );

        newAssetFrame.addTab("مشخصات اولیه", primaryTab);

        subAssetTab.setVisible(true);

        jLabel8.setFont(new java.awt.Font("Web Yekan", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("تعریف دارایی جدید - زیردارایی‌ها");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane1.setViewportView(jTree1);

        assetsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        assetsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(160, 196, 255));
        headerPanel.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ردیف");
        headerPanel.add(jLabel14);
        jLabel14.setBounds(270, 0, 40, 30);

        jLabel15.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("نام دارایی");
        headerPanel.add(jLabel15);
        jLabel15.setBounds(170, 0, 60, 30);

        jLabel19.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("حذف");
        headerPanel.add(jLabel19);
        jLabel19.setBounds(0, 0, 80, 30);

        assetsPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 30));

        assetsScrollPane.setViewportView(assetsPanel);

        jButton34.setBackground(new java.awt.Color(60, 0, 91));
        jButton34.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jButton34.setForeground(new java.awt.Color(1, 1, 1));
        jButton34.setText("اضافه کردن زیردارایی");
        jButton34.setFocusPainted(false);
        jButton34.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subAssetTabLayout = new javax.swing.GroupLayout(subAssetTab.getContentPane());
        subAssetTab.getContentPane().setLayout(subAssetTabLayout);
        subAssetTabLayout.setHorizontalGroup(
            subAssetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subAssetTabLayout.createSequentialGroup()
                .addGroup(subAssetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(subAssetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(subAssetTabLayout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(assetsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(subAssetTabLayout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        subAssetTabLayout.setVerticalGroup(
            subAssetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subAssetTabLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subAssetTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(assetsScrollPane))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        newAssetFrame.addTab("زیردارایی", subAssetTab);

        humanTab.setVisible(true);

        jLabel7.setFont(new java.awt.Font("Web Yekan", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("تعریف دارایی جدید - مشخصات دارایی انسانی");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextField11.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField11.setText("محمدرضا");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jTextField12.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField12.setText("بشارتی");
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField13.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField13.setText("۰۰۳۱۲۳۱۲۴۳");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jTextField14.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField14.setText("۱۲۱۲-۱");
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jTextField15.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField15.setText("پشتیبان دارایی در دانشگاه شریف");
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        jLabel77.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel77.setText("توضیحات");
        jLabel77.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel78.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel78.setText("کد ‍پرسنلی");
        jLabel78.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel79.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel79.setText("شماره ملی");
        jLabel79.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel80.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel80.setText("نام خانوداگی");
        jLabel80.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel81.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel81.setText("نام");
        jLabel81.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout humanTabLayout = new javax.swing.GroupLayout(humanTab.getContentPane());
        humanTab.getContentPane().setLayout(humanTabLayout);
        humanTabLayout.setHorizontalGroup(
            humanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(humanTabLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, humanTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(humanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(humanTabLayout.createSequentialGroup()
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(humanTabLayout.createSequentialGroup()
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(humanTabLayout.createSequentialGroup()
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(humanTabLayout.createSequentialGroup()
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(humanTabLayout.createSequentialGroup()
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106))
        );
        humanTabLayout.setVerticalGroup(
            humanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(humanTabLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(humanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(humanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(humanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(humanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(humanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 64, Short.MAX_VALUE))
        );

        newAssetFrame.addTab("دارایی انسانی", humanTab);

        placeTab.getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Web Yekan", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("تعریف دارایی جدید - مشخصات دارایی مکان‌مند");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        placeTab.getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 0, 427, 38);

        jLabel55.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel55.setText("در حال دریافت اطلاعات مکانی دارایی ...");
        jLabel55.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        placeTab.getContentPane().add(jLabel55);
        jLabel55.setBounds(410, 80, 201, 24);

        jLabel56.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel56.setText("اطلاعات مکانی با موفقیت دریافت شد.");
        jLabel56.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        placeTab.getContentPane().add(jLabel56);
        jLabel56.setBounds(420, 130, 190, 24);

        jLabel57.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel57.setText("عرض جغرافیایی: 35.6961 درجه‌ی شمالی");
        jLabel57.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        placeTab.getContentPane().add(jLabel57);
        jLabel57.setBounds(390, 180, 220, 24);

        jLabel58.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel58.setText("طول جغرافیایی: 51.4231 درجه‌ی شرقی");
        jLabel58.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        placeTab.getContentPane().add(jLabel58);
        jLabel58.setBounds(400, 230, 213, 24);

        newAssetFrame.addTab("دارایی مکان‌مند", placeTab);

        physicalTab.getContentPane().setLayout(null);

        jLabel62.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel62.setText("مشخصات ظاهری دارایی");
        jLabel62.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        physicalTab.getContentPane().add(jLabel62);
        jLabel62.setBounds(490, 80, 123, 24);

        jTextField3.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText("برج سفید رنگ. چهارپایه");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        physicalTab.getContentPane().add(jTextField3);
        jTextField3.setBounds(310, 80, 135, 32);

        jLabel5.setFont(new java.awt.Font("Web Yekan", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("تعریف دارایی جدید - مشخصات دارایی فیزیکی");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        physicalTab.getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 0, 420, 38);

        buttonGroup5.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("بیمه دارد");
        jRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jRadioButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        physicalTab.getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(390, 120, 100, 22);

        buttonGroup5.add(jRadioButton1);
        jRadioButton1.setText("بیمه ندارد");
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jRadioButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        physicalTab.getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(540, 120, 84, 22);

        jLabel63.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel63.setText("شرح بیمه");
        jLabel63.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        physicalTab.getContentPane().add(jLabel63);
        jLabel63.setBounds(560, 170, 49, 24);

        jTextField1.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("بیمه‌ی ساختمانی بیمه‌ی ایران تا آخر ۹۷");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        physicalTab.getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 170, 208, 32);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setSelected(true);
        jRadioButton4.setText("سند دارد");
        jRadioButton4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jRadioButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        physicalTab.getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(540, 230, 79, 22);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("سند ندارد");
        jRadioButton5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jRadioButton5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        physicalTab.getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(400, 230, 84, 22);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("سند موضوعیت ندارد");
        jRadioButton3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jRadioButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        physicalTab.getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(180, 230, 154, 22);

        jTextField5.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setText("سند شش دانگ به نام سازمان شهرداری تهران");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        physicalTab.getContentPane().add(jTextField5);
        jTextField5.setBounds(200, 280, 248, 32);

        jLabel64.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel64.setText("شرح سند");
        jLabel64.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        physicalTab.getContentPane().add(jLabel64);
        jLabel64.setBounds(560, 280, 51, 24);

        newAssetFrame.addTab("دارایی فیزیکی", physicalTab);

        finalTab.setVisible(true);

        jLabel6.setFont(new java.awt.Font("Web Yekan", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("تعریف دارایی جدید - ذخیره");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        finalAssetName.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        finalAssetName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        finalAssetName.setText("میدان آزادی");

        finalAssetUID.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        finalAssetUID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        finalAssetUID.setText("azadi.squar.371");

        jLabel48.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel48.setText("UID");

        jLabel52.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel52.setText("نام دارایی");

        finalAssetName1.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        finalAssetName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        finalAssetName1.setText("دارایی انسان نیست");

        finalAssetName2.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        finalAssetName2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        finalAssetName2.setText("دارایی مرکب نیست");

        finalAssetName3.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        finalAssetName3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        finalAssetName3.setText("دارایی مکان‌مند نیست");

        finalAssetName4.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        finalAssetName4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        finalAssetName4.setText("دارایی فیزیکی نیست");

        jButton35.setBackground(new java.awt.Color(60, 0, 91));
        jButton35.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jButton35.setForeground(new java.awt.Color(1, 1, 1));
        jButton35.setText("ذخیره‌ی دارایی");
        jButton35.setFocusPainted(false);
        jButton35.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout finalTabLayout = new javax.swing.GroupLayout(finalTab.getContentPane());
        finalTab.getContentPane().setLayout(finalTabLayout);
        finalTabLayout.setHorizontalGroup(
            finalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finalTabLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel6)
                .addContainerGap(245, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finalTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(finalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finalTabLayout.createSequentialGroup()
                        .addGroup(finalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(finalTabLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(finalAssetName)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel52))
                            .addGroup(finalTabLayout.createSequentialGroup()
                                .addComponent(finalAssetUID)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finalTabLayout.createSequentialGroup()
                        .addGroup(finalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(finalAssetName2)
                            .addComponent(finalAssetName1)
                            .addComponent(finalAssetName3)
                            .addComponent(finalAssetName4))
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finalTabLayout.createSequentialGroup()
                        .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(298, 298, 298))))
        );
        finalTabLayout.setVerticalGroup(
            finalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finalTabLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(38, 38, 38)
                .addGroup(finalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finalAssetName)
                    .addComponent(jLabel52))
                .addGap(16, 16, 16)
                .addGroup(finalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finalAssetUID)
                    .addComponent(jLabel48))
                .addGap(18, 18, 18)
                .addComponent(finalAssetName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalAssetName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalAssetName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalAssetName4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        newAssetFrame.addTab("نهایی کردن", finalTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newAssetFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newAssetFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assetNameActionPerformed

    private void assetUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assetUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assetUIDActionPerformed

    private void isCompositeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isCompositeActionPerformed
        if (isComposite.isSelected()){
            newAssetFrame.setEnabledAt(1, true);
        }else{
            newAssetFrame.setEnabledAt(1, false);
        }
    }//GEN-LAST:event_isCompositeActionPerformed

    private void hasPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasPlaceActionPerformed
        if (hasPlace.isSelected()){
            newAssetFrame.setEnabledAt(3, true);
        }else{
            newAssetFrame.setEnabledAt(3, false);
        }
    }//GEN-LAST:event_hasPlaceActionPerformed

    private void isHumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isHumanActionPerformed
        if (isHuman.isSelected()){
            newAssetFrame.setEnabledAt(2, true);
        }else{
            newAssetFrame.setEnabledAt(2, false);
        }
    }//GEN-LAST:event_isHumanActionPerformed

    private void isPhysicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isPhysicalActionPerformed
        if (isPhysical.isSelected()){
            newAssetFrame.setEnabledAt(4, true);
        }else{
            newAssetFrame.setEnabledAt(4, false);
        }
    }//GEN-LAST:event_isPhysicalActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void assetNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_assetNameFocusLost
        finalAssetName.setText(assetName.getText());
    }//GEN-LAST:event_assetNameFocusLost

    private void assetUIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_assetUIDFocusLost
        finalAssetUID.setText(assetUID.getText());
    }//GEN-LAST:event_assetUIDFocusLost

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAssetFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assetName;
    private javax.swing.JTextField assetUID;
    private javax.swing.JPanel assetsPanel;
    private javax.swing.JScrollPane assetsScrollPane;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel finalAssetName;
    private javax.swing.JLabel finalAssetName1;
    private javax.swing.JLabel finalAssetName2;
    private javax.swing.JLabel finalAssetName3;
    private javax.swing.JLabel finalAssetName4;
    private javax.swing.JLabel finalAssetUID;
    private javax.swing.JInternalFrame finalTab;
    private javax.swing.JCheckBox hasPlace;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JInternalFrame humanTab;
    private javax.swing.JCheckBox isComposite;
    private javax.swing.JCheckBox isHuman;
    private javax.swing.JCheckBox isPhysical;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTree jTree1;
    private javax.swing.JTabbedPane newAssetFrame;
    private javax.swing.JInternalFrame physicalTab;
    private javax.swing.JInternalFrame placeTab;
    private javax.swing.JInternalFrame primaryTab;
    private javax.swing.JInternalFrame subAssetTab;
    // End of variables declaration//GEN-END:variables
}
