/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.rule;

import GUI.asset.addLabel.AssetAttachLabelFrame;
import GUI.asset.newAsset.NewAssetFrame;
import asset.Asset;
import asset.AssetCatalogue;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
import label.AttachedLabel;
import rule.*;

/**
 *
 * @author bagher
 */
public class ApplyRuleForm extends javax.swing.JFrame {

    private final Asset inMeasureAsset;
    private int mode = 1;
    public static final int MOD_NEW = 1;
    public static final int MOD_UPDATE = 2;
    public static final int MOD_LABEL = 3;
    private ApplyRule apr;
    private NewAssetFrame newAssetFrame;
    private AssetAttachLabelFrame attachLabelFrame;

    public ApplyRuleForm(Asset inMeasureAsset, int mode, NewAssetFrame newAssetFrame) {
        this.mode = mode;
        initComponents();
        this.newAssetFrame = newAssetFrame;
        this.inMeasureAsset = inMeasureAsset;
        inMeasureProperty.doClick();
        baseProperty.doClick();
        inMeasureAssetName.setText(inMeasureAsset.getName());
        baseAsset.setModel(new JComboBox<Asset>(AssetCatalogue.getInstace().getAssets().toArray(new Asset[AssetCatalogue.getInstace().getAssets().size()])).getModel());
        rulesComboBox.setModel(new JComboBox<Rule>(ConsistencyRules.getInstance().getRules().toArray(new Rule[ConsistencyRules.getInstance().getRules().size()])).getModel());
        importantComboBox.setModel(new JComboBox<String>(ApplyRule.importanceComment).getModel());
        this.constantField.setVisible(false);
        jPanel1.add(constantField);
        constantField.setLocation(baseAsset.getX(), baseAsset.getY());

    }

    public ApplyRuleForm(ApplyRule applyRuleForm, int mode) {
        this.apr = applyRuleForm;
        this.mode = mode;
        initComponents();
        baseAsset.setModel(new JComboBox<Asset>(AssetCatalogue.getInstace().getAssets().toArray(new Asset[AssetCatalogue.getInstace().getAssets().size()])).getModel());
        rulesComboBox.setModel(new JComboBox<Rule>(ConsistencyRules.getInstance().getRules().toArray(new Rule[ConsistencyRules.getInstance().getRules().size()])).getModel());

        this.inMeasureAsset = applyRuleForm.getInMeasureAsset();
        baseAsset.setSelectedItem(applyRuleForm.getBaseAsset());
        if (applyRuleForm.getInMeasurePropertyNumber() == -1) {
            inMeasureProperty.doClick();
            inMeasureData.setSelectedIndex(applyRuleForm.getInMeasurePropertyNumber());
        } else {
            inMeasureLabel.doClick();
            inMeasureData.setSelectedItem(applyRuleForm.getInMeasureLabel());
        }
        if (applyRuleForm.getBasePropertyNumber() == -1) {
            baseProperty.doClick();
            baseData.setSelectedIndex(applyRuleForm.getBasePropertyNumber());
        } else {
            baseLabel.doClick();
            baseData.setSelectedItem(applyRuleForm.getBaseLabel());
        }
        rulesComboBox.setSelectedIndex(applyRuleForm.getRule());
        importantComboBox.setModel(new JComboBox<String>(ApplyRule.importanceComment).getModel());
        inMeasureAssetName.setText(inMeasureAsset.getName());
        jPanel1.add(constantField);
        this.constantField.setVisible(false);
        constantField.setLocation(baseAsset.getX(), baseAsset.getY());

    }

    public ApplyRuleForm(Asset asset, AttachedLabel label, int mode, AssetAttachLabelFrame alf) {
        initComponents();
        this.mode = mode;
        this.attachLabelFrame = alf;
        this.inMeasureAsset = asset;
        inMeasureLabel.setSelected(true);
        inMeasureLabel.setEnabled(false);
        inMeasureProperty.setEnabled(false);
        baseProperty.doClick();
        inMeasureAssetName.setText(inMeasureAsset.getName());
        AttachedLabel[] imMeasureL = {label};
        inMeasureData.setModel(new JComboBox<AttachedLabel>(imMeasureL).getModel());
        baseAsset.setModel(new JComboBox<Asset>(AssetCatalogue.getInstace().getAssets().toArray(new Asset[AssetCatalogue.getInstace().getAssets().size()])).getModel());
        rulesComboBox.setModel(new JComboBox<Rule>(ConsistencyRules.getInstance().getRules().toArray(new Rule[ConsistencyRules.getInstance().getRules().size()])).getModel());
        importantComboBox.setModel(new JComboBox<String>(ApplyRule.importanceComment).getModel());
        jPanel1.add(constantField);
        this.constantField.setVisible(false);
        constantField.setLocation(baseAsset.getX(), baseAsset.getY());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inMeasureLoP = new javax.swing.ButtonGroup();
        baseLoP = new javax.swing.ButtonGroup();
        saveRule = new javax.swing.JButton();
        rulesComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        baseAsset = new javax.swing.JComboBox();
        baseData = new javax.swing.JComboBox();
        jLabel52 = new javax.swing.JLabel();
        AoC = new javax.swing.JLabel();
        baseProperty = new javax.swing.JRadioButton();
        baseLabel = new javax.swing.JRadioButton();
        conCommeent = new javax.swing.JLabel();
        isConstant = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        inMeasureAssetName = new javax.swing.JLabel();
        inMeasureData = new javax.swing.JComboBox();
        inMeasureProperty = new javax.swing.JRadioButton();
        inMeasureLabel = new javax.swing.JRadioButton();
        jLabel58 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        importantComboBox = new javax.swing.JComboBox();
        constantField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveRule.setBackground(new java.awt.Color(205, 141, 238));
        saveRule.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        saveRule.setForeground(new java.awt.Color(1, 1, 1));
        saveRule.setText("ذخیره‌ی قانون");
        saveRule.setFocusPainted(false);
        saveRule.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        saveRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRuleActionPerformed(evt);
            }
        });
        getContentPane().add(saveRule, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 250, 130, 30));

        rulesComboBox.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        rulesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "قانون مورد نظر را انتخاب کنید", " " }));
        rulesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(rulesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 95, 151, -1));

        jLabel3.setFont(new java.awt.Font("Web Yekan", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("تعریف قانون سازگار سنجی");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 240, 51));

        jPanel1.setBackground(new java.awt.Color(213, 177, 213));

        baseAsset.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        baseAsset.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "همین دارایی" }));
        baseAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseAssetActionPerformed(evt);
            }
        });

        baseData.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        baseData.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "مقدار مورد نظر را انتخاب کنید" }));
        baseData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseDataActionPerformed(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel52.setText("مقدار مبنا");

        AoC.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        AoC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AoC.setText("دارایی:");

        baseLoP.add(baseProperty);
        baseProperty.setSelected(true);
        baseProperty.setText("ویژگی اولیه");
        baseProperty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        baseProperty.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        baseProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basePropertyActionPerformed(evt);
            }
        });

        baseLoP.add(baseLabel);
        baseLabel.setText("برچسب");
        baseLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        baseLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        baseLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseLabelActionPerformed(evt);
            }
        });

        conCommeent.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        conCommeent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        conCommeent.setText("قانون سازگار سنجی روی:");

        isConstant.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        isConstant.setText("مقدار ثابت");
        isConstant.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        isConstant.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        isConstant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isConstantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(baseData, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(baseAsset, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(isConstant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AoC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(baseLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(baseProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(conCommeent, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isConstant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AoC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baseAsset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baseProperty)
                    .addComponent(baseLabel))
                .addGap(18, 18, 18)
                .addComponent(conCommeent, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(baseData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 69, 226, -1));

        jPanel2.setBackground(new java.awt.Color(213, 177, 213));

        jLabel55.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel55.setText("دارایی:");

        jLabel56.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel56.setText("مقدار تحت سنجش");

        inMeasureAssetName.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        inMeasureAssetName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        inMeasureAssetName.setText("نامشخص");

        inMeasureData.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        inMeasureData.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "مقدار مورد نظر را انتخاب کنید" }));
        inMeasureData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inMeasureDataActionPerformed(evt);
            }
        });

        inMeasureLoP.add(inMeasureProperty);
        inMeasureProperty.setSelected(true);
        inMeasureProperty.setText("ویژگی اولیه");
        inMeasureProperty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        inMeasureProperty.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        inMeasureProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inMeasurePropertyActionPerformed(evt);
            }
        });

        inMeasureLoP.add(inMeasureLabel);
        inMeasureLabel.setText("برچسب");
        inMeasureLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        inMeasureLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        inMeasureLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inMeasureLabelActionPerformed(evt);
            }
        });

        jLabel58.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel58.setText("قانون سازگار سنجی روی:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(inMeasureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inMeasureProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(inMeasureAssetName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel55))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(inMeasureData, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel56, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inMeasureAssetName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inMeasureProperty)
                    .addComponent(inMeasureLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inMeasureData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 69, -1, -1));

        jLabel57.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel57.setText("قانون سازگار سنجی:");
        getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 63, -1, 26));

        cancel.setBackground(new java.awt.Color(205, 141, 238));
        cancel.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        cancel.setForeground(new java.awt.Color(1, 1, 1));
        cancel.setText("لغو");
        cancel.setFocusPainted(false);
        cancel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 292, 130, 30));

        jLabel60.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel60.setText("سطح اهمیت:");
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 147, -1, 26));

        importantComboBox.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        importantComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "قانون مورد نظر را انتخاب کنید", " " }));
        importantComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importantComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(importantComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 179, 151, -1));

        constantField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        constantField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                constantFieldActionPerformed(evt);
            }
        });
        constantField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                constantFieldFocusLost(evt);
            }
        });
        getContentPane().add(constantField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRuleActionPerformed
        if (mode == MOD_NEW) {
            Asset selectedBaseAsset = (Asset) baseAsset.getSelectedItem();
            if (isConstant.isSelected()) {
                if (inMeasureProperty.isSelected()) {
                    inMeasureAsset.getRules().add(new ApplyRule(inMeasureAsset, selectedBaseAsset, inMeasureData.getSelectedIndex(), baseData.getSelectedIndex(), null, null, rulesComboBox.getSelectedIndex(), importantComboBox.getSelectedIndex(), constantField.getText()));
                } else if (inMeasureLabel.isSelected()) {
                    AttachedLabel selectedInMeasureLabel = (AttachedLabel) inMeasureData.getSelectedItem();
                    AttachedLabel selectedBaseLabel = (AttachedLabel) baseData.getSelectedItem();
                    selectedInMeasureLabel.getRules().add(new ApplyRule(inMeasureAsset, selectedBaseAsset, -1, -1, selectedInMeasureLabel, selectedBaseLabel, rulesComboBox.getSelectedIndex(), importantComboBox.getSelectedIndex(), constantField.getText()));
                }
            } else {
                if (inMeasureProperty.isSelected() && baseProperty.isSelected()) {
                    inMeasureAsset.getRules().add(new ApplyRule(inMeasureAsset, selectedBaseAsset, inMeasureData.getSelectedIndex(), baseData.getSelectedIndex(), null, null, rulesComboBox.getSelectedIndex(), importantComboBox.getSelectedIndex(), null));

                } else if (inMeasureProperty.isSelected() && baseLabel.isSelected()) {
                    AttachedLabel selectedBaseLabel = (AttachedLabel) baseData.getSelectedItem();
                    inMeasureAsset.getRules().add(new ApplyRule(inMeasureAsset, selectedBaseAsset, inMeasureData.getSelectedIndex(), -1, null, selectedBaseLabel, rulesComboBox.getSelectedIndex(), importantComboBox.getSelectedIndex(), null));
                } else if (baseProperty.isSelected() && inMeasureLabel.isSelected()) {
                    AttachedLabel selectedInMeasureLabel = (AttachedLabel) inMeasureData.getSelectedItem();
                    selectedInMeasureLabel.getRules().add(new ApplyRule(inMeasureAsset, selectedBaseAsset, -1, baseData.getSelectedIndex(), selectedInMeasureLabel, null, rulesComboBox.getSelectedIndex(), importantComboBox.getSelectedIndex(), null));
                } else if (baseLabel.isSelected() && inMeasureLabel.isSelected()) {
                    AttachedLabel selectedInMeasureLabel = (AttachedLabel) inMeasureData.getSelectedItem();
                    AttachedLabel selectedBaseLabel = (AttachedLabel) baseData.getSelectedItem();
                    selectedInMeasureLabel.getRules().add(new ApplyRule(inMeasureAsset, selectedBaseAsset, -1, -1, selectedInMeasureLabel, selectedBaseLabel, rulesComboBox.getSelectedIndex(), importantComboBox.getSelectedIndex(), null));
                }
            }
            this.newAssetFrame.loadRuleLabelComponnets();
        } else if (mode == MOD_UPDATE) {
            if (apr == null) {
                this.dispose();
                JOptionPane.showMessageDialog(null, "مشکلی در بروزرسانی دارایی پیش‌آمده است.", "خطا", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                apr.setBaseAsset((Asset) baseAsset.getSelectedItem());
                apr.setInMeasureAsset(inMeasureAsset);
                if (baseProperty.isSelected()) {
                    apr.setBasePropertyNumber(baseData.getSelectedIndex());
                    apr.setBaseLabel(null);
                } else {
                    apr.setBasePropertyNumber(-1);
                    apr.setBaseLabel((AttachedLabel) baseData.getSelectedItem());
                }
                if (inMeasureProperty.isSelected()) {
                    apr.setInMeasurePropertyNumber(inMeasureData.getSelectedIndex());
                    apr.setInMeasureLabel(null);
                } else {
                    apr.setInMeasurePropertyNumber(-1);
                    apr.setInMeasureLabel((AttachedLabel) inMeasureData.getSelectedItem());
                }
                apr.setRule(rulesComboBox.getSelectedIndex());
            }
            this.newAssetFrame.loadRuleLabelComponnets();
        } else if (mode == MOD_LABEL) {
            Asset selectedBaseAsset = (Asset) baseAsset.getSelectedItem();
            if (isConstant.isSelected()) {
                if (inMeasureProperty.isSelected()) {
                    inMeasureAsset.getRules().add(new ApplyRule(inMeasureAsset, selectedBaseAsset, inMeasureData.getSelectedIndex(), baseData.getSelectedIndex(), null, null, rulesComboBox.getSelectedIndex(), importantComboBox.getSelectedIndex(), constantField.getText()));
                } else if (inMeasureLabel.isSelected()) {
                    AttachedLabel selectedInMeasureLabel = (AttachedLabel) inMeasureData.getSelectedItem();
                    AttachedLabel selectedBaseLabel = (AttachedLabel) baseData.getSelectedItem();
                    selectedInMeasureLabel.getRules().add(new ApplyRule(inMeasureAsset, selectedBaseAsset, -1, -1, selectedInMeasureLabel, selectedBaseLabel, rulesComboBox.getSelectedIndex(), importantComboBox.getSelectedIndex(), constantField.getText()));
                }
            } else {
                if (baseProperty.isSelected()) {
                    //TODO improve adding applyrule
                    AttachedLabel selectedInMeasureLabel = (AttachedLabel) inMeasureData.getSelectedItem();
                    selectedInMeasureLabel.getRules().add(new ApplyRule(inMeasureAsset, selectedBaseAsset, -1, baseData.getSelectedIndex(), selectedInMeasureLabel, null, rulesComboBox.getSelectedIndex(), importantComboBox.getSelectedIndex(), null));
//                if (inMeasureAsset.getUID().equals(selectedBaseAsset.getUID())) {

//                } else {
//                    selectedBaseAsset.getRules().add(new ApplyRule(inMeasureAsset, selectedBaseAsset, -1, baseData.getSelectedIndex(), selectedInMeasureLabel, null, rulesComboBox.getSelectedIndex(), importantComboBox.getSelectedIndex()));
//                }
                } else if (baseLabel.isSelected()) {
                    AttachedLabel selectedInMeasureLabel = (AttachedLabel) inMeasureData.getSelectedItem();
                    AttachedLabel selectedBaseLabel = (AttachedLabel) baseData.getSelectedItem();
                    selectedInMeasureLabel.getRules().add(new ApplyRule(inMeasureAsset, selectedBaseAsset, -1, -1, selectedInMeasureLabel, selectedBaseLabel, rulesComboBox.getSelectedIndex(), importantComboBox.getSelectedIndex(), null));
//                selectedBaseLabel.getRules().add(new ApplyRule(inMeasureAsset, selectedBaseAsset, -1, -1, selectedInMeasureLabel, selectedBaseLabel, rulesComboBox.getSelectedIndex(), importantComboBox.getSelectedIndex()));
                }
            }
            this.attachLabelFrame.loadRuleLabelComponnets();
        }
        this.dispose();
        if (this.mode == MOD_NEW) {
            JOptionPane.showMessageDialog(null, "قانون مورد نظر شما با موفقیت ثبت شد.", "پیام", JOptionPane.INFORMATION_MESSAGE);
        } else if (mode == MOD_UPDATE) {
            JOptionPane.showMessageDialog(null, "قانون مورد نظر با موفقیت بروزرسانی شد.", "پیام", JOptionPane.INFORMATION_MESSAGE);
        } else if (mode == MOD_LABEL) {
            JOptionPane.showMessageDialog(null, "قانون مورد نظر شما با موفقیت ثبت شد.", "پیام", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_saveRuleActionPerformed

    private void rulesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rulesComboBoxActionPerformed

    private void baseAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseAssetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baseAssetActionPerformed

    private void baseDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baseDataActionPerformed

    private void inMeasureDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inMeasureDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inMeasureDataActionPerformed

    private void inMeasureLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inMeasureLabelActionPerformed
        if (inMeasureAsset.getAttachedLabels().length == 0) {
            String[] noLabel = {"برچسبی به دارایی الصاق نشده است."};
            inMeasureData.setModel(new javax.swing.JComboBox(noLabel).getModel());
        } else {
            inMeasureData.setModel(new javax.swing.JComboBox<AttachedLabel>(inMeasureAsset.getAttachedLabels()).getModel());
        }
    }//GEN-LAST:event_inMeasureLabelActionPerformed

    private void inMeasurePropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inMeasurePropertyActionPerformed
        inMeasureData.setModel(new javax.swing.JComboBox<String>(Asset.assetProperties).getModel());
    }//GEN-LAST:event_inMeasurePropertyActionPerformed

    private void basePropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basePropertyActionPerformed
        baseData.setModel(new javax.swing.JComboBox<String>(Asset.assetProperties).getModel());
    }//GEN-LAST:event_basePropertyActionPerformed

    private void baseLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseLabelActionPerformed
        Asset tmpAsset = (Asset) baseAsset.getSelectedItem();
        if (tmpAsset.getAttachedLabels().length == 0) {
            String[] noLabel = {"برچسبی به دارایی الصاق نشده است."};
            baseData.setModel(new javax.swing.JComboBox(noLabel).getModel());
        } else {
            baseData.setModel(new javax.swing.JComboBox<AttachedLabel>(tmpAsset.getAttachedLabels()).getModel());
        }
    }//GEN-LAST:event_baseLabelActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void importantComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importantComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importantComboBoxActionPerformed

    private void isConstantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isConstantActionPerformed
        if (isConstant.isSelected()) {
            baseAsset.setVisible(false);
            constantField.setVisible(true);
            AoC.setText("مقدار ثابت");
            baseLabel.setVisible(false);
            baseData.setVisible(false);
            baseProperty.setVisible(false);
            conCommeent.setVisible(false);
        } else {
            baseAsset.setVisible(true);
            constantField.setVisible(false);
            AoC.setText("دارایی");
            baseLabel.setVisible(true);
            baseData.setVisible(true);
            baseProperty.setVisible(true);
            conCommeent.setVisible(false);
        }
    }//GEN-LAST:event_isConstantActionPerformed

    private void constantFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_constantFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_constantFieldActionPerformed

    private void constantFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_constantFieldFocusLost
//        finalAssetName.setText(constantField.getText());
//        if (mode == MOD_NEW) {
//            finalAsset.setName(constantField.getText());
//        }
//        subAssetTree.repaint();
//        loadRuleLabelComponnets();
    }//GEN-LAST:event_constantFieldFocusLost

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ApplyRuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ApplyRuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ApplyRuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ApplyRuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Asset asset = new Asset();
//                asset.setName("منم منم");
//                asset.setUID("manam manam");
//                new ApplyRuleForm(asset, 1).setVisible(true);
//
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AoC;
    private javax.swing.JComboBox baseAsset;
    private javax.swing.JComboBox baseData;
    private javax.swing.JRadioButton baseLabel;
    private javax.swing.ButtonGroup baseLoP;
    private javax.swing.JRadioButton baseProperty;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel conCommeent;
    private javax.swing.JTextField constantField;
    private javax.swing.JComboBox importantComboBox;
    private javax.swing.JLabel inMeasureAssetName;
    private javax.swing.JComboBox inMeasureData;
    private javax.swing.JRadioButton inMeasureLabel;
    private javax.swing.ButtonGroup inMeasureLoP;
    private javax.swing.JRadioButton inMeasureProperty;
    private javax.swing.JCheckBox isConstant;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox rulesComboBox;
    private javax.swing.JButton saveRule;
    // End of variables declaration//GEN-END:variables
}
