/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Nov 29, 2013, 2:04:52 PM
 */
package GUI.operation;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import operation.Operation;
import operation.OperationCatalogue;

/**
 *
 * @author Bagher
 */
public class NewOperationFrame extends javax.swing.JFrame {
    public static final int MOD_UPDATE = 1;
    public static final int MOD_NEW = 2;
            
    private Operation operation;
    private OperaionListManagementFrame operaionListManagementFrame;

    /** Creates new form MainFrame
     * @param operaionListManagementFrame */
    public NewOperationFrame(OperaionListManagementFrame operaionListManagementFrame) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e) {
          System.out.println("Error setting native LAF: " + e);
        }
        this.operaionListManagementFrame = operaionListManagementFrame;
        this.operation = new Operation();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        saveOperationButton = new javax.swing.JButton();
        operationNameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("سامانه‌ی مدیریت ‍پیکربندی شهردای");
        setBackground(new java.awt.Color(152, 152, 152));
        setBounds(new java.awt.Rectangle(50, 50, 750, 500));
        setMinimumSize(new java.awt.Dimension(750, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Web Yekan", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("تعریف عملیات جدید");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 431, 70));

        jLabel47.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel47.setText("نام علمیات");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        saveOperationButton.setBackground(new java.awt.Color(254, 254, 254));
        saveOperationButton.setFont(new java.awt.Font("Web Yekan", 0, 15)); // NOI18N
        saveOperationButton.setForeground(new java.awt.Color(1, 1, 1));
        saveOperationButton.setText("ذخیره عملیات");
        saveOperationButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 139, 255), 1, true));
        saveOperationButton.setFocusPainted(false);
        saveOperationButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        saveOperationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveOperationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveOperationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, 30));

        operationNameTextField.setFont(new java.awt.Font("XB Zar", 0, 15)); // NOI18N
        operationNameTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        operationNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(operationNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveOperationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveOperationButtonActionPerformed
        if(operationNameTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "برای عملیات نامی انتخاب نشده است.", "خطا", JOptionPane.ERROR_MESSAGE);
            return;
        }
        operation.setName(operationNameTextField.getText());
        OperationCatalogue.getInstace().addOperation(operation);
        operation = new Operation();
        operationNameTextField.setText("");
        operaionListManagementFrame.loadOperationComponents();
    }//GEN-LAST:event_saveOperationButtonActionPerformed

    private void operationNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operationNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new NewLabelFrame().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel47;
    private javax.swing.JTextField operationNameTextField;
    private javax.swing.JButton saveOperationButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
